"""initial_schema

Revision ID: a2164e1442c3
Revises: 
Create Date: 2026-03-04 16:31:36.637771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2164e1442c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entry',
    sa.Column('audit_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_type', sa.Enum('RETAIL', 'CORPORATE', 'SME', 'GOVERNMENT', name='customertype'), nullable=False),
    sa.Column('industry_sector', sa.String(length=100), nullable=True),
    sa.Column('credit_rating', sa.String(length=20), nullable=True),
    sa.Column('internal_rating', sa.String(length=20), nullable=True),
    sa.Column('external_rating', sa.String(length=20), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('is_watchlist', sa.Boolean(), nullable=True),
    sa.Column('is_defaulted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('macro_scenario',
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('probability_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('gdp_growth_rate', sa.JSON(), nullable=True),
    sa.Column('inflation_rate', sa.JSON(), nullable=True),
    sa.Column('ugx_usd_exchange_rate', sa.JSON(), nullable=True),
    sa.Column('unemployment_rate', sa.JSON(), nullable=True),
    sa.Column('interest_rate', sa.JSON(), nullable=True),
    sa.Column('agriculture_index', sa.JSON(), nullable=True),
    sa.Column('manufacturing_index', sa.JSON(), nullable=True),
    sa.Column('services_index', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_table('parameter_set',
    sa.Column('parameter_id', sa.String(length=50), nullable=False),
    sa.Column('parameter_type', sa.Enum('PD', 'LGD', 'EAD', 'SICR_THRESHOLD', name='parametertype'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('customer_segment', sa.String(length=50), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('credit_rating', sa.String(length=20), nullable=True),
    sa.Column('collateral_type', sa.String(length=50), nullable=True),
    sa.Column('parameter_value', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('parameter_curve', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('parameter_id')
    )
    op.create_table('financial_instrument',
    sa.Column('instrument_id', sa.String(length=50), nullable=False),
    sa.Column('instrument_type', sa.Enum('TERM_LOAN', 'OVERDRAFT', 'BOND', 'COMMITMENT', name='instrumenttype'), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('origination_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('classification', sa.Enum('AMORTIZED_COST', 'FVOCI', 'FVTPL', name='classification'), nullable=True),
    sa.Column('classification_date', sa.Date(), nullable=True),
    sa.Column('business_model', sa.Enum('HOLD_TO_COLLECT', 'HOLD_TO_COLLECT_AND_SELL', 'OTHER', name='businessmodel'), nullable=True),
    sa.Column('sppi_test_result', sa.Boolean(), nullable=True),
    sa.Column('current_stage', sa.Enum('STAGE_1', 'STAGE_2', 'STAGE_3', name='stage'), nullable=True),
    sa.Column('stage_date', sa.Date(), nullable=True),
    sa.Column('initial_recognition_pd', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'WRITTEN_OFF', 'DERECOGNIZED', name='instrumentstatus'), nullable=True),
    sa.Column('days_past_due', sa.Integer(), nullable=True),
    sa.Column('is_poci', sa.Boolean(), nullable=True),
    sa.Column('is_modified', sa.Boolean(), nullable=True),
    sa.Column('modification_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.create_table('collateral',
    sa.Column('collateral_id', sa.String(length=50), nullable=False),
    sa.Column('instrument_id', sa.String(length=50), nullable=False),
    sa.Column('collateral_type', sa.Enum('REAL_ESTATE', 'CASH', 'SECURITIES', 'EQUIPMENT', name='collateraltype'), nullable=False),
    sa.Column('original_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('haircut_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('net_realizable_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_perfected', sa.Boolean(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['financial_instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('collateral_id')
    )
    op.create_table('ecl_calculation',
    sa.Column('calculation_id', sa.String(length=50), nullable=False),
    sa.Column('instrument_id', sa.String(length=50), nullable=False),
    sa.Column('reporting_date', sa.Date(), nullable=False),
    sa.Column('stage', sa.Enum('STAGE_1', 'STAGE_2', 'STAGE_3', name='stage'), nullable=False),
    sa.Column('pd', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('lgd', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('ead', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ecl_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('calculation_method', sa.String(length=20), nullable=True),
    sa.Column('time_horizon', sa.String(length=20), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('base_scenario_ecl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('upside_scenario_ecl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('downside_scenario_ecl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('scenario_weights', sa.JSON(), nullable=True),
    sa.Column('calculation_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('calculation_duration_ms', sa.Integer(), nullable=True),
    sa.Column('parameters_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['financial_instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('calculation_id')
    )
    op.create_table('stage_transition',
    sa.Column('transition_id', sa.String(length=50), nullable=False),
    sa.Column('instrument_id', sa.String(length=50), nullable=False),
    sa.Column('transition_date', sa.Date(), nullable=False),
    sa.Column('from_stage', sa.Enum('STAGE_1', 'STAGE_2', 'STAGE_3', name='stage'), nullable=False),
    sa.Column('to_stage', sa.Enum('STAGE_1', 'STAGE_2', 'STAGE_3', name='stage'), nullable=False),
    sa.Column('sicr_indicators', sa.JSON(), nullable=True),
    sa.Column('pd_at_transition', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('pd_at_origination', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('pd_change_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('days_past_due', sa.Integer(), nullable=True),
    sa.Column('transition_reason', sa.Text(), nullable=True),
    sa.Column('is_automatic', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['financial_instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('transition_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_transition')
    op.drop_table('ecl_calculation')
    op.drop_table('collateral')
    op.drop_table('financial_instrument')
    op.drop_table('parameter_set')
    op.drop_table('macro_scenario')
    op.drop_table('customer')
    op.drop_table('audit_entry')
    # ### end Alembic commands ###
